#!/usr/bin/env bash

#
# Filename:       /etc/libvirt/hooks/dohibernate
# Description:    Allow host hibernation while libvirt domain is hibernating.
# Author(s):      Alex Portell <github.com/portellam>
# Maintainer(s):  Alex Portell <github.com/portellam>
#

HOOK_NAME="dohibernate"
PREFIX_ERROR="An error occurred:"
PREFIX_PROMPT="libvirt-qemu ${HOOK_NAME}:"
DOMAIN_NAME="${1}"
OPERATION="${2}"

function start_service
{
  if ! systemctl enable libvirt-dohibernate@"${DOMAIN_NAME}" &> /dev/null; then
    echo "${PREFIX_PROMPT} ${PREFIX_ERROR} Failed to enable 'libvirt-dohibernate@${DOMAIN_NAME}' service." >&2
    return 1
  fi

  if ! systemctl start libvirt-dohibernate@"${DOMAIN_NAME}" &> /dev/null; then
    echo "${PREFIX_PROMPT} ${PREFIX_ERROR} Failed to start 'libvirt-dohibernate@${DOMAIN_NAME}' service." >&2
    return 1
  fi

  echo "${PREFIX_PROMPT} Started 'libvirt-dohibernate@${DOMAIN_NAME}' service."
}

function stop_service
{
  if ! systemctl disable libvirt-dohibernate@"${DOMAIN_NAME}" &> /dev/null; then
    echo "${PREFIX_PROMPT} ${PREFIX_ERROR} Failed to disable 'libvirt-dohibernate@${DOMAIN_NAME}' service." >&2
    return 1
  fi

  if ! systemctl stop libvirt-dohibernate@"${DOMAIN_NAME}" &> /dev/null; then
    echo "${PREFIX_PROMPT} ${PREFIX_ERROR} Failed to stop 'libvirt-dohibernate@${DOMAIN_NAME}' service." >&2
    return 1
  fi

  echo "${PREFIX_PROMPT} Stopped 'libvirt-dohibernate@${DOMAIN_NAME}' service."
}

case "${OPERATION}" in
  "prepare")
    start_service ;;
  "release")
    stop_service ;;
esac