#!/usr/bin/env bash

#
# Filename:       /etc/libvirt/hooks/dosleep
# Description:    Allow host sleep while libvirt domain is sleeping.
# Author(s):      Alex Portell <github.com/portellam>
# Maintainer(s):  Alex Portell <github.com/portellam>
#

HOOK_NAME="dosleep"
PREFIX_ERROR="An error occurred:"
PREFIX_PROMPT="libvirt-qemu ${HOOK_NAME}:"
DOMAIN_NAME="${1}"
OPERATION="${2}"
SERVICE_NAME="libvirt-${HOOK_NAME}@${DOMAIN_NAME}"

function start_service
{
  if ! systemctl enable "${SERVICE_NAME}" &> /dev/null; then
    echo "${PREFIX_PROMPT} ${PREFIX_ERROR} Failed to enable '${SERVICE_NAME}' service." >&2
    return 1
  fi

  if ! sudo systemctl start "${SERVICE_NAME}" &> /dev/null; then
    echo "${PREFIX_PROMPT} ${PREFIX_ERROR} Failed to start '${SERVICE_NAME}' service." >&2
    return 1
  fi

  echo "${PREFIX_PROMPT} Started '${SERVICE_NAME}' service."
}

function stop_service
{
  if ! systemctl disable "${SERVICE_NAME}" &> /dev/null; then
    echo "${PREFIX_PROMPT} ${PREFIX_ERROR} Failed to disable '${SERVICE_NAME}' service." >&2
    return 1
  fi

  if ! sudo systemctl stop "${SERVICE_NAME}" &> /dev/null; then
    echo "${PREFIX_PROMPT} ${PREFIX_ERROR} Failed to stop '${SERVICE_NAME}' service." >&2
    return 1
  fi

  echo "${PREFIX_PROMPT} Stopped '${SERVICE_NAME}' service."
}

case "${OPERATION}" in
  "prepare")
    start_service ;;
  "release")
    stop_service ;;
esac