#!/usr/bin/env bash

#
# Filename:       /etc/libvirt/hooks/nosleep
# Description:    Prevent host sleep while libvirt domain is running.
# URL(s):         https://web.archive.org/web/20220808031554/https://old.reddit.com/r/VFIO/comments/8ypedp/for_anyone_getting_issues_with_their_guest_when/
# Author(s):      sm-Fifteen <reddit.com/u/sm-Fifteen>
# Maintainer(s):  Alex Portell <github.com/portellam>
#

# <functions>
  function main
  {
    # <params>
      dir="$( dirname "$( realpath "${0}" )" )/"
      source="${dir}set-service"

      domain_name="${1}"
      hook_name="$( basename "${0}" )"
      this_service_name="libvirt-${hook_name}@${domain_name}.service"
      real_service_name="libvirt-${hook_name}@.service"
      service_full_path="/etc/systemd/system/libvirt-${real_service_name}"
      local -ar arguments=( "${this_service_name}" "${service_full_path}" "$@" )
    # </params>

    # <sources>
      source "${source}"
    # </sources>

    main "${arguments[@]}"
  }
# </functions>

# <code>
  main "$@"
# </code>