#!/usr/bin/env bash

#
# Filename:       /etc/libvirt/hooks/nosleep
# Description:    Prevent host sleep while libvirt domain is running.
# URL(s):         https://web.archive.org/web/20220808031554/https://old.reddit.com/r/VFIO/comments/8ypedp/for_anyone_getting_issues_with_their_guest_when/
# Author(s):      sm-Fifteen <reddit.com/u/sm-Fifteen>
# Maintainer(s):  Alex Portell <codeberg.org/portellam> <github.com/portellam>
# Version:        1.0.0
#

# <params>
  DIR="$( dirname "$( realpath "${0}" )" )/"
  SOURCE="${DIR}set-service"
  DOMAIN_NAME="${1}"
  HOOK_NAME="$( basename "${0}" )"
  SERVICE_NAME="libvirt-${HOOK_NAME}@${DOMAIN_NAME}.service"
  ARGUMENTS=( "${SERVICE_NAME}" "$@" )
# </params>

# <functions>
  function main
  {
    source "${SOURCE}"
    main "${ARGUMENTS[@]}"
  }
# </functions>

# <code>
  main
# </code>