#!/usr/bin/env bash

#
# Filename:       /etc/libvirt/hooks/nosleep
# Description:    Prevent host sleep while libvirt domain is running.
# URL(s):         https://web.archive.org/web/20220808031554/https://old.reddit.com/r/VFIO/comments/8ypedp/for_anyone_getting_issues_with_their_guest_when/
# Author(s):      sm-Fifteen <reddit.com/u/sm-Fifteen>
# Maintainer(s):  Alex Portell <codeberg.org/portellam> <github.com/portellam>
# Version:        1.0.0
#

#
# params
#
  STR_DIR="$( dirname "$( realpath "${0}" )" )/"
  STR_SOURCE="${STR_DIR}set-service"
  STR_DOMAIN_NAME="${1}"
  STR_HOOK_NAME="$( basename "${0}" )"
  STR_SERVICE_NAME="libvirt-${STR_HOOK_NAME}@${STR_DOMAIN_NAME}.service"
  ARR_ARGUMENTS=( "${STR_SERVICE_NAME}" "$@" )

#
# logic
#
  #
  # DESC:     Call the source file and execute the expected function "main" for it.
  # WARNING:  Without a source file declared, infinite recursion will occur.
  # RETURN:   Always return code from called source file.
  #
    function main
    {
      source "${STR_SOURCE}"

      # calls the function "main" from the source file
      main "${ARR_ARGUMENTS[@]}"
    }

#
# main
#
  main