#!/usr/bin/env bash

#
# Filename:       /etc/libvirt/hooks/qemu
# Description:    List of Libvirt hooks to invoke.
# Author(s):      Alex Portell <codeberg.org/portellam> <github.com/portellam>
# Maintainer(s):  Alex Portell <codeberg.org/portellam> <github.com/portellam>
# Version:        1.0.0
#

# <remarks>If a script exits with an error, exit Libvirt.</remarks>
# <sets>
  set -eo pipefail
# </sets>

# <params>
  DIR="$( dirname "$( realpath "${0}" )" )/"
# </params>

# <functions>
  # <summary>
  # Update list here. Example:
  #   "PATH_TO_FILE" "$@"
  # </summary>
  # <note>Do not add 'set-service'. This script file is called as a source file to other files (example: 'nosleep').</note>
  function main
  {
    "${DIR}isolcpu" "$@" || return 1
    "${DIR}nosleep" "$@" || return 1
    "${DIR}set-hooks" "$@" || return 1
  }
# </functions>

# <code>
  main "$@"
# </code>