#!/usr/bin/env bash

#
# Filename:       /etc/libvirt/hooks/qemu
# Author(s):      Alex Portell <github.com/portellam>
# Maintainer(s):  Alex Portell <github.com/portellam>
#

# <remarks>If a script exits with an error, exit Libvirt.</remarks>
set -e

# <params>
  MASTER_HOOK="${0}"
  DIR_NAME="$( dirname $( realpath "${0}" ) )/hooks/"
  HOOKS_LIST_EXCLUDES_MASTER_HOOK+=( $( find -L "${DIR_NAME}" -maxdepth 1 ! -name "${MASTER_HOOK}" -type f ) )
# </params>

# <functions>
  function execute_hooks
  {
    for hook in "${HOOKS_LIST_EXCLUDES_MASTER_HOOK[@]}"; do
      eval ${hook} "$@"
    done
  }
# </functions>

# <code>
  execute_hooks
# </code>