#!/usr/bin/env bash

#
# Filename:       /etc/libvirt/hooks/qemu
# Description:    List of Libvirt hooks to invoke.
# Author(s):      Alex Portell <codeberg.org/portellam> <github.com/portellam>
# Maintainer(s):  Alex Portell <codeberg.org/portellam> <github.com/portellam>
# Version:        1.0.0
#

#
# params
#
  DIR="$( dirname "$( realpath "${0}" )" )/"

#
# logic
#
  #
  # DESC:   main execution.
  # $@:     the arguments as an array.
  # RETURN: If successful, return 0.
  #         If not, return 1.
  #
  #
    function main
    {
      # NOTE:     add new scripts to invoke here ( "PATH_TO_FILE" "$@" ).
      # WARNING:  do not add 'set-service'. This may cause infinite recursion.
      if ! "${DIR}isolcpu" "$@" \
        || "${DIR}nosleep" "$@" \
        || "${DIR}set-hooks" "$@"; then
        return 1
      fi

      return 0
    }

#
# main
#
  set -eo pipefail  # exit Libvirt on script error.
  main "$@"