#!/usr/bin/env bash

#
# Filename:       /etc/libvirt/hooks/set-hooks
# Description:    Create symlinks of domain-specific hooks.
# Author(s):      Alex Portell <codeberg.org/portellam> <github.com/portellam>
# Maintainer(s):  Alex Portell <codeberg.org/portellam> <github.com/portellam>
# Version:        1.0.0
#

#
# Stateful hooks:
#   Execute hooks that change given different Libvirt domain state input
#   (example: start or stop).
#   Place hooks in subdirectories found in '/etc/libvirt/hooks/set-hooks':
#     * start-only
#     * stop-only
#     * start-and-stop
#

#
# params
#
  STR_DOMAIN_NAME="${1}"

  #
  # DESC: append output
  #
    STR_PREFIX_PROMPT="libvirt-qemu $( basename "${0}" )"
    STR_PREFIX_ERROR="${STR_PREFIX_PROMPT}An error occurred: "
    STR_PREFIX_FAIL="${STR_PREFIX_PROMPT}Failure: "
    STR_PREFIX_PASS="${STR_PREFIX_PROMPT}Success: "
    STR_PREFIX_SKIP="${STR_PREFIX_PROMPT}Skipped: "

  STR_HOOKS_BASE_DIR="$( dirname $( realpath "${0}" ) )/"
  STR_DOMAIN_NAME_BASE_DIR="${STR_HOOKS_BASE_DIR}qemu.d/${STR_DOMAIN_NAME}/"
  STR_DOMAIN_NAME_START_DIR="${STR_DOMAIN_NAME_BASE_DIR}started/begin/"
  STR_DOMAIN_NAME_STOP_DIR="${STR_DOMAIN_NAME_BASE_DIR}stopped/end/"

  STR_STATEFUL_HOOKS_DIR="${0}.d/"
  STR_STATEFUL_HOOKS_START_ONLY_DIR="${STR_STATEFUL_HOOKS_DIR}start-only/"
  STR_STATEFUL_HOOKS_STOP_ONLY_DIR="${STR_STATEFUL_HOOKS_DIR}stop-only/"
  STR_STATEFUL_HOOKS_BOTH_DIR="${STR_STATEFUL_HOOKS_DIR}start-and-stop/"

  ARR_STATEFUL_HOOKS_START_LIST=( \
    $( find -L "${STR_STATEFUL_HOOKS_START_ONLY_DIR}" -maxdepth 1 -type f ) \
  )

  ARR_STATEFUL_HOOKS_START_LIST+=( \
    $( find -L "${STR_STATEFUL_HOOKS_BOTH_DIR}" -maxdepth 1 -type f ) \
  )

  ARR_STATEFUL_HOOKS_STOP_LIST=( \
    $( find -L "${STR_STATEFUL_HOOKS_STOP_ONLY_DIR}" -maxdepth 1 -type f ) \
  )

  ARR_STATEFUL_HOOKS_STOP_LIST+=( \
    $( find -L "${STR_STATEFUL_HOOKS_BOTH_DIR}" -maxdepth 1 -type f ) \
  )

#
# logic
#
  #
  # DESC:     Setup hooks for given domain.
  # RETURN:   If domain is not valid or domain hooks are setup, return 0.
  #           If domain hooks are not setup, return 1.
  #
    function main
    {
      IFS=$'\n'
      local -r str_output="Set hooks"
      log_output "${str_output}"

      if ! is_valid_domain; then
        log_skip "${str_output}"
        return 0
      fi

      if ! get_paths_for_domain \
        || ! get_hooks; then
        log_fail "${str_output}"
        return 1
      fi

      setup_stateful_hooks
      return 0
    }

  #
  # DESC: loggers
  #
    #
    # DESC:   Log the output as an error.
    # $1:     the output as a string.
    # RETURN: Always return 0.
    #
      function log_error
      {
        echo -e "${STR_PREFIX_ERROR}${1}" >&2
        return 0
      }

    #
    # DESC:   Log the output as a fail.
    # $1:     the output as a string.
    # RETURN: Always return 0.
    #
      function log_fail
      {
        echo -e "${STR_PREFIX_FAIL}${1}" >&2
        return 0
      }

    #
    # DESC:   Log the output as a fail.
    # $1:     the output as a string.
    # RETURN: Always return 0.
    #
      function log_output
      {
        echo -e "${STR_PREFIX_PROMPT}${1}" >&1
        return 0
      }

    #
    # DESC:   Log the output as a pass.
    # $1:     the output as a string.
    # RETURN: Always return 0.
    #
      function log_pass
      {
        echo -e "${STR_PREFIX_PASS}${1}" >&1
        return 0
      }

    #
    # DESC:   Log the output as a skip.
    # $1:     the output as a string.
    # RETURN: Always return 0.
    #
      function log_skip
      {
        echo -e "${STR_PREFIX_SKIP}${1}" >&1
        return 0
      }

  #
  # DESC: getters
  #
    #
    # DESC:     Get paths for the domain.
    # RETURN:   If paths are created, return 0.
    #           If paths are not created, return 1.
    #
      function get_paths_for_domain
      {
        if ! create_directory "${STR_DOMAIN_NAME_BASE_DIR}" \
          || ! create_directory "${STR_DOMAIN_NAME_START_DIR}" \
          || ! create_directory "${STR_DOMAIN_NAME_STOP_DIR}"; then
          log_error "Failed to create directories for Libvirt domain '${STR_DOMAIN}'."
          return 1
        fi

        return 0
      }

    #
    # DESC:     Get hooks for the domain.
    # RETURN:   If hooks are found, return 0.
    #           If hooks are not found, return 1.
    #
      function get_hooks
      {
        for str_hook_name in "${HOOKS_LIST[@]}"; do
          if [[ ! -e "${HOOK_BASE_DIR}${str_hook_name}" ]]; then
            log_error "Failed to find hook(s) for Libvirt domain '${STR_DOMAIN}'."
            return 1
          fi
        done

        return 0
      }

  #
  # DESC: setters
  #
    #
    # DESC:     Create the directory.
    # $1:       the directory name as a string.
    # RETURN:   If the directory is created, return 0.
    #           If not, return 1.
    #
      function create_directory
      {
        local -r str_dir="${1}"

        if [[ -d "${str_dir}" ]] \
          && ! mkdir --parents "${str_dir}" &> /dev/null; then
          log_error "Failed to create directory '${str_dir}'."
          return 1
        fi

        return 0
      }

    #
    # DESC:     Set start hook for given domain.
    # $1:       the domain name as a string.
    # RETURN:   If the start hook exists and is set or does not exist, return 0.
    #           If not, return 1.
    #
      function set_start_hook_for_domain
      {
        local -r str_domain="${str_domain}"

        if [[ -z "${str_domain}" ]] \
          || [[ ! -e "${STR_DOMAIN_NAME_START_DIR}${str_domain}" ]]; then
          return 0
        fi

        if ! ln -s "${STR_DOMAIN_NAME_START_DIR}${str_domain}" \
          "${HOOK_BASE_DIR}${str_domain}" &> /dev/null; then
          log_error "Failed to set symlinks for start hook '${str_domain}'."
          return 1
        fi

        if ! chmod +x "${STR_DOMAIN_NAME_START_DIR}${str_domain}" &> /dev/null; then
          log_error "Failed to set file permissions for start hook '${str_domain}'."
          return 1
        fi

        return 0
      }

    #
    # DESC:     Set stop hook for given domain.
    # $1:       the domain name as a string.
    # RETURN:   If the stop hook exists and is set or does not exist, return 0.
    #           If not, return 1.
    #
      function set_stop_hook_for_domain
      {
        local -r str_domain="${1}"

        if [[ -z "${1}" ]] \
          || [[ ! -e "${STR_DOMAIN_NAME_STOP_DIR}${str_domain}" ]]; then
          return 0
        fi

        if ! ln -s "${STR_DOMAIN_NAME_STOP_DIR}${str_domain}" \
          "${HOOK_BASE_DIR}${str_domain}" &> /dev/null; then
          log_error "Failed to set symlinks for stop hook '${str_domain}'."
          return 1
        fi

        if ! chmod +x "${STR_DOMAIN_NAME_STOP_DIR}${str_domain}" &> /dev/null; then
          log_error "Failed to set file permissions for stop hook '${str_domain}'."
          return 1
        fi

        return 0
      }

    #
    # DESC:     Setup hooks for the domain.
    # RETURN:   Always return 0.
    #
      function setup_stateful_hooks
      {
        for str_hook in "${ARR_STATEFUL_HOOKS_START_LIST[@]}"; do
          if ! set_start_hook_for_domain "${str_hook}"; then
            unset_hook_for_domain "${str_hook}"
          fi
        done

        for str_hook in "${ARR_STATEFUL_HOOKS_STOP_LIST[@]}"; do
          if ! set_stop_hook_for_domain "${str_hook}"; then
            unset_hook_for_domain "${str_hook}"
          fi
        done

        return 0
      }

    #
    # DESC:     Unset hook for given domain.
    # $1:       the domain name as a string.
    # RETURN:   If the hook exists and is unset or does not exist, return 0.
    #           If not, return 1.
    #
      function unset_hook_for_domain
      {
        local -r str_domain="${1}"

        if [[ -z "${str_domain}" ]]; then
          return 0
        fi

        if [[ ! -e "${STR_DOMAIN_NAME_START_DIR}${str_domain}" ]] \
          && ! rm -rf "${STR_DOMAIN_NAME_START_DIR}${str_domain}" &> /dev/null; then
          log_error "Failed to unset symlinks for start hook '${str_domain}'."
          return 1
        fi

        if [[ ! -z "${STR_DOMAIN_NAME_STOP_DIR}${str_domain}" ]] \
          && ! rm -rf "${STR_DOMAIN_NAME_STOP_DIR}${str_domain}" &> /dev/null; then
          log_error "Failed to unset symlinks for stop hook '${str_domain}'."
          return 1
        fi

        return 0
      }

  #
  # DESC:   Is domain valid.
  # RETURN: If the domain is valid, return 0.
  #         If not, return 1.
  #
    function is_valid_domain
    {
      if [[ ! -z "${STR_DOMAIN_NAME}" ]]; then
        log_error "Stateful hook requires a Libvirt domain '${STR_DOMAIN}'."
        return 1
      fi

      return 0
    }

#
# main
#
  main "$@"