#!/usr/bin/env bash

#
# Filename:       /etc/libvirt/hooks/set-services
# Description:    Start or stop systemd service for given domain.
# Author(s):      Alex Portell <github.com/portellam>
# Maintainer(s):  Alex Portell <github.com/portellam>
#

# <params>
  OPERATION="${2}"

  PREFIX_ERROR="An error occurred:"
  PREFIX_PROMPT="libvirt-qemu $( basename "${0}" ):"

  SERVICE_DIR="${0}.d/"
  SERVICE_LIST=$( find -L "${SERVICE_DIR}" -maxdepth 1 -type f )
# </params>

# <functions>
  function print_prompt
  {
    echo -e "${PREFIX_PROMPT} ${1}"
  }

  function print_prompt_to_log
  {
    print_prompt "${1}" >&2
  }

  function print_prompt_and_error_to_log
  {
    print_prompt_to_log "${PREFIX_ERROR} ${1}"
  }

  function start_all_services
  {
    for service in "${SERVICE_LIST[@]}"; do
      start_this_service "${service}" || return 1
    done
  }

  function start_this_service
  {
    local service="${1}"

    if ! systemctl start "${service}" &> /dev/null; then
      print_prompt_and_error_to_log "Failed to start '${service}' service."
      return 1
    fi

    print_prompt_to_log "Started '${service}' service."
  }

  function stop_all_services
  {
    for service in "${SERVICE_LIST[@]}"; do
      stop_this_service "${service}" || return 1
    done
  }

  function stop_this_service
  {
    local service="${1}"

    if ! systemctl stop "${service}" &> /dev/null; then
      print_prompt_and_error_to_log "Failed to stop '${service}' service."
      return 1
    fi

    print_prompt_to_log "Stopped '${service}' service."
  }
# </functions>

# <code>
  case "${OPERATION}" in
    "prepare")
      start_all_services ;;
    "release")
      stop_all_services ;;
  esac
# </code>